const mongoose = require("mongoose");
// importing the mongoose
// User model means what are different type of data fields we want to store in data base like name , surname , mobile no, email , etc....
// How to create Models
//1) Import Mongoose
//2) Create Mongoose Schema (structure of any song)
//3) Create a model

const song = new mongoose.Schema({
    // This are the following fields we want to store about any song
	name:
    {
        type :String,
        required:true,
    },
    thumbnail:
    {
        type:String,
        required:true
    },
    track:
    {
        type:String,
        required:true
    },
    artist:
    {
        // as we want to store the data of artist we will store it in the user database only since an user can be artist or vic versa so instead of making 2 different models we combine it in one only 
        // the type mongoose.Types.ObjectId  is the same type of object ID which is generated by a mongoose when a user data is added into it , mongoose allocate a unique ID to each and every data model 
        // ref tells us about from what type of object we want to fetch the ID
        type:mongoose.Types.ObjectId,
        ref:"User",
        required:true
    }
});
// Now we create a model using model function model("Model-Name", "Schema-Name")
module.exports = mongoose.model('Song', song);
// const SongModel = mongoose.model("Song", "song");
// module.exports = SongModel;
